### ISSUE TITLE
Can't local files/webpages be added?

### ISSUE THREAD

**Issue by Huub62** [pltnkv/tabme#5]
I used another bookmark manager but tried TabMe. To my surprise when I moved my open tabs to a folder they all showed up but when choosing "Open All" the local files didnt show up anymore. Also when i clicked on them in the folder they didnt open .... all i could do was choose Copy URL and then open a new tab and past the url.

Is this a bug or is this just not a feature of TabMe. If it is a feature then TabMe is unfortunatly not for me, because i have many local files bookmarked from projects i am working on.

For the rest TabMe really looks very good!

**Comment by pltnkv** [comment]
Hey @Huub62 , thank you for the feedback. No access to local files was not intended.
I have added permission to support "file:///"
```
"optional_host_permissions": [
    "<all_urls>"
  ]
```

However, it will not be enough, and Chrome needs the user to confirm access to local files manually.

1) Open chrome://extensions/
2) Find Tabme and click "Details" 
3) Enable toggle "Allow access to file URLs"

I sent an updated version to review; it should be available soon.
